# Generated by Django 3.1.7 on 2021-05-02 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='nombre completo')),
                ('email', models.CharField(max_length=150, verbose_name='correo electrónico')),
                ('cell_phone', models.CharField(max_length=9, verbose_name='num. de celular')),
                ('address', models.CharField(max_length=150, verbose_name='dirección')),
                ('district', models.CharField(max_length=100, verbose_name='distrito')),
                ('city', models.CharField(max_length=150, verbose_name='ciudad o País')),
                ('reference', models.TextField(max_length=200, verbose_name='referencia')),
                ('address_detail', models.CharField(max_length=200, verbose_name='N° de puerta/Lte/Mz/Dpto/Piso')),
                ('address_gps', models.JSONField(blank=True, max_length=100, null=True, verbose_name='dirección gps')),
                ('default', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'dirección',
                'verbose_name_plural': 'direcciones',
            },
        ),
    ]
