# Generated by Django 3.1.7 on 2021-05-23 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cell_phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El núm. de celular no es válido, es formato válido es: 999999999', regex='^\\+?1?\\d{9,9}$')], verbose_name='num. de celular'),
        ),
        migrations.AlterField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Principal'),
        ),
    ]
