# Generated by Django 3.1.7 on 2021-06-18 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20210617_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='correo electrónico (opcional)'),
        ),
    ]
