# Generated by Django 3.1.7 on 2021-03-16 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('dni', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=100)),
                ('cell_phone', models.CharField(max_length=9)),
                ('cell_phone2', models.CharField(max_length=9)),
                ('current_address', models.CharField(max_length=200)),
                ('references', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='drivers/')),
                ('payment_account', models.CharField(max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
