# Generated by Django 3.1.7 on 2021-03-24 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('code', models.CharField(max_length=9, unique=True, verbose_name='código')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('cell_phone', models.CharField(max_length=9, verbose_name='Num. de celular')),
                ('cell_phone2', models.CharField(blank=True, max_length=9, null=True, verbose_name='Num. de celular 2')),
                ('address', models.CharField(max_length=100, verbose_name='dirección')),
                ('references', models.TextField(max_length=200, verbose_name='referencias')),
                ('district', models.CharField(max_length=100, verbose_name='distrito')),
                ('address_gps', models.JSONField(blank=True, max_length=100, null=True, verbose_name='dirección actual')),
                ('payment_account', models.CharField(max_length=14, verbose_name='número de cuenta')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'motorizado',
                'verbose_name_plural': 'motorizados',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, verbose_name='número de serie de la moto')),
                ('license_code', models.CharField(max_length=10, verbose_name='código de brevete')),
                ('license_plate_number', models.CharField(max_length=10, verbose_name='número de placa')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado')),
            ],
        ),
    ]
