# Generated by Django 3.1.7 on 2021-03-24 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'vehiculo', 'verbose_name_plural': 'vehiculos'},
        ),
    ]
