# Generated by Django 3.1.7 on 2021-03-17 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'motorizado', 'verbose_name_plural': 'motorizados'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.CharField(max_length=100, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cell_phone',
            field=models.CharField(max_length=9, verbose_name='Num. de celular'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cell_phone2',
            field=models.CharField(max_length=9, verbose_name='Num. de celular 2'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='code',
            field=models.CharField(max_length=10, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='current_address',
            field=models.CharField(max_length=200, verbose_name='dirección actual'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='district',
            field=models.CharField(max_length=100, verbose_name='distrito'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='payment_account',
            field=models.CharField(max_length=14, verbose_name='número de cuenta'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='references',
            field=models.TextField(max_length=200, verbose_name='referencias'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
