# Generated by Django 3.1.7 on 2021-03-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210316_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
