# Generated by Django 3.1.7 on 2021-04-30 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_paymentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
    ]
