# Generated by Django 3.1.7 on 2021-03-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20210317_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dni',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
