# Generated by Django 3.1.7 on 2021-05-24 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='cell_phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El núm. de celular no es válido, el formato válido es: 999999999', regex='^\\+?1?\\d{9,9}$')], verbose_name='Num. de celular'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='cell_phone2',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Num. de celular 2 (opcional)'),
        ),
    ]
