# Generated by Django 3.1.7 on 2021-03-17 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_auto_20210317_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=10, verbose_name='número de serie de la moto')),
                ('license_code', models.CharField(max_length=10, verbose_name='código de brevete')),
                ('license_plate_number', models.CharField(max_length=10, verbose_name='número de placa')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado')),
            ],
        ),
    ]
