# Generated by Django 3.1.7 on 2021-03-24 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('driver_code', models.CharField(max_length=12, verbose_name='código de motorizado')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de tienda')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='logo de la tienda')),
                ('social_media', models.JSONField(blank=True, null=True, verbose_name='redes sociales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
    ]
