# Generated by Django 3.1.7 on 2021-03-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Núm. de celular'),
        ),
    ]
