# Generated by Django 3.1.7 on 2021-03-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_gps',
            field=models.JSONField(blank=True, null=True, verbose_name='Dirección GPS'),
        ),
    ]
