# Generated by Django 3.1.7 on 2021-04-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_cell_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Identificador'),
        ),
    ]
