# Generated by Django 3.1.7 on 2021-05-23 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210503_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El núm. de celular no es válido, es formato válido es: 999999999', regex='^\\+?1?\\d{9,9}$')], verbose_name='Núm. de celular'),
        ),
    ]
