# Generated by Django 3.1.7 on 2021-06-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_prices', '0002_auto_20210421_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPaymentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(default=0, verbose_name='mínimo de pedidos')),
                ('max', models.IntegerField(default=0, verbose_name='máximo de pedidos')),
                ('percentage', models.IntegerField(default=0, verbose_name='porcentaje de pago')),
            ],
            options={
                'verbose_name': 'tarifario de pago del motorizado',
                'verbose_name_plural': 'tarifarios de pago del motorizado',
            },
        ),
    ]
