# Generated by Django 3.1.7 on 2021-06-23 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_prices', '0003_driverpaymentrate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'permissions': (('can_view_budget', 'Puede ver el presupuesto'),), 'verbose_name': 'precio del servicio', 'verbose_name_plural': 'precios del servicio'},
        ),
    ]
