# Generated by Django 3.1.7 on 2021-04-11 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=5, verbose_name='valoración')),
                ('experience', models.TextField(max_length=250, verbose_name='experiencia')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='cliente')),
            ],
        ),
    ]
