# Generated by Django 3.1.7 on 2021-04-11 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valorations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoration',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='valoración'),
        ),
    ]
