# Generated by Django 3.1.7 on 2021-04-11 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210324_1648'),
        ('valorations', '0002_auto_20210410_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoration',
            options={'permissions': (('can_view_valoration', 'puede ver la(s) valoración(es)'), ('can_add_valoration', 'puede realizar una valoración')), 'verbose_name': 'valoración', 'verbose_name_plural': 'valoraciones'},
        ),
        migrations.AddField(
            model_name='valoration',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado'),
            preserve_default=False,
        ),
    ]
