# Generated by Django 3.1.7 on 2021-04-11 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valorations', '0003_auto_20210410_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoration',
            options={'verbose_name': 'valoración', 'verbose_name_plural': 'valoraciones'},
        ),
    ]
