# Generated by Django 3.1.7 on 2021-04-21 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_paymentaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_orders', models.IntegerField(default=0, verbose_name='total de pedidos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='total pagado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha del pago')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado')),
            ],
            options={
                'verbose_name': 'pago del motorizado',
                'verbose_name_plural': 'pagos del motorizado',
            },
        ),
    ]
