# Generated by Django 3.1.7 on 2021-06-17 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_you_create_orders', models.BooleanField(default=False, verbose_name='¿puedes registrar pedidos?')),
                ('time_limit', models.TimeField(blank=True, default=datetime.time(23, 0), verbose_name='tiempo de cierre del sistema')),
            ],
        ),
    ]
