# Generated by Django 3.1.7 on 2021-06-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'configuración', 'verbose_name_plural': 'configuraciones'},
        ),
        migrations.AddField(
            model_name='setting',
            name='message_origin',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='mensaje para el cliente del recojo de sus paquetes'),
        ),
    ]
