# Generated by Django 3.1.7 on 2021-03-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='users/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
