# Generated by Django 3.1.7 on 2021-03-24 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellidos')),
                ('email', models.CharField(max_length=150, verbose_name='correo electrónico')),
                ('cell_phone', models.CharField(max_length=9, verbose_name='num. de celular')),
                ('image', models.ImageField(blank=True, null=True, upload_to='details-order/%Y/%m/%d/', verbose_name='imagen del paquete')),
                ('address_destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_destiny', to='addresses.address', verbose_name='dirección de destino')),
                ('address_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_origin', to='addresses.address', verbose_name='dirección de recojo')),
            ],
        ),
    ]
