# Generated by Django 3.1.7 on 2021-04-19 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0005_order_promo_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=150, verbose_name='tamaño')),
                ('contain', models.CharField(max_length=100, verbose_name='¿Qué contiene?')),
                ('value', models.CharField(max_length=150, verbose_name='valor del paquete')),
                ('image', models.ImageField(blank=True, null=True, upload_to='details-order/%Y/%m/%d/', verbose_name='imagen del paquete')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='nota')),
                ('distance', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='distancia')),
                ('price_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de tarifa')),
                ('address_destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_destiny', to='addresses.address', verbose_name='dirección de destino')),
                ('address_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_origin', to='addresses.address', verbose_name='dirección de recojo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'detalle',
                'verbose_name_plural': 'detalles',
            },
        ),
    ]
