# Generated by Django 3.1.7 on 2021-03-25 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payed_image'),
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido'),
            preserve_default=False,
        ),
    ]
