# Generated by Django 3.1.7 on 2021-05-04 03:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20210502_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedelivered',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='nota (opcional)'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='details-order/%Y/%m/%d/', verbose_name='imagen del paquete (opcional)'),
        ),
    ]
