# Generated by Django 3.1.7 on 2021-03-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_detail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='descripción del paquete'),
        ),
        migrations.AddField(
            model_name='detail',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='distancia'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de tarifa'),
        ),
    ]
