# Generated by Django 3.1.7 on 2021-05-23 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20210522_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200, verbose_name='ubicación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='details.detail', verbose_name='paquete')),
            ],
            options={
                'verbose_name': 'Seguimiento de pedido',
                'verbose_name_plural': 'Seguimiento de pedidos',
            },
        ),
    ]
