# Generated by Django 3.1.7 on 2021-03-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20210325_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail',
            options={'verbose_name': 'detalle', 'verbose_name_plural': 'detalles'},
        ),
    ]
