# Generated by Django 3.1.7 on 2021-05-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_trackingorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Código de seguimiento'),
        ),
    ]
