# Generated by Django 3.1.7 on 2021-03-26 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20210325_1742'),
        ('details', '0004_auto_20210325_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='address_destiny',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_destiny', to='addresses.address', verbose_name='dirección de destino'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='address_origin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_origin', to='addresses.address', verbose_name='dirección de recojo'),
        ),
    ]
