# Generated by Django 3.1.7 on 2021-05-04 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_packagedelivered_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivered',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='orders/delivered/%Y/%m/%d/', verbose_name='imagen o foto 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packagedelivered',
            name='image2',
            field=models.ImageField(upload_to='orders/delivered/%Y/%m/%d/', verbose_name='imagen o foto 2'),
        ),
    ]
