# Generated by Django 3.1.7 on 2021-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20210524_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='price_rate_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio de tarifa anterior (Cod. promo especial)'),
        ),
    ]
