# Generated by Django 3.1.7 on 2021-05-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_created_at'),
        ('details', '0005_auto_20210503_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivered',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.detail', verbose_name='dirección de envío'),
        ),
        migrations.AlterField(
            model_name='packagedelivered',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado'),
        ),
    ]
