# Generated by Django 3.1.7 on 2021-04-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_auto_20210326_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='sub_total',
            new_name='price_rate',
        ),
    ]
