# Generated by Django 3.1.7 on 2021-06-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_auto_20210526_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndeliveryaddress',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='esta entregado'),
        ),
        migrations.AddField(
            model_name='assignoriginaddress',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='esta recepcionado'),
        ),
    ]
