# Generated by Django 3.1.7 on 2021-06-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0008_auto_20210602_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigndeliveryaddress',
            name='date_delivered',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de entrega'),
        ),
        migrations.AddField(
            model_name='assignoriginaddress',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de recepción'),
        ),
    ]
