# Generated by Django 3.1.7 on 2021-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_auto_20210602_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivered',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='orders/delivered/%Y/%m/%d/', verbose_name='imagen o foto 2'),
        ),
    ]
