# Generated by Django 3.1.7 on 2021-06-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0010_auto_20210616_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedelivered',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='details.detail', verbose_name='paquete a entregar'),
        ),
    ]
