# Generated by Django 3.1.7 on 2021-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('discount', models.FloatField(default=0.0, verbose_name='descuento')),
                ('valid_from', models.DateTimeField(verbose_name='fecha de inicio')),
                ('valid_to', models.DateTimeField(verbose_name='fecha de vencimiento')),
                ('used_to', models.BooleanField(default=False, verbose_name='usado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'código promocional',
                'verbose_name_plural': 'código promocionales',
            },
        ),
    ]
