# Generated by Django 3.1.7 on 2021-04-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='used_to',
            new_name='used',
        ),
    ]
