# Generated by Django 3.1.7 on 2021-05-25 23:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0003_auto_20210421_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='special',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer], verbose_name='descuento especial'),
        ),
    ]
