# Generated by Django 3.1.7 on 2021-05-26 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0004_promocode_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer], verbose_name='porcentaje de descuento'),
        ),
    ]
