# Generated by Django 3.1.7 on 2021-05-26 22:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0005_auto_20210526_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='special',
            field=models.IntegerField(default=0, validators=[django.core.validators.validate_integer], verbose_name='descuento especial S/'),
        ),
    ]
