# Generated by Django 3.1.7 on 2021-05-04 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promo_codes', '0003_auto_20210421_0828'),
        ('clients', '0004_auto_20210503_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Registrado'), ('CO', 'Completado'), ('CA', 'Cancelado')], default='RE', max_length=50, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('type_ticket', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta')], default='FACTURA', max_length=10, verbose_name='Comprobante electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('payed_image', models.ImageField(blank=True, null=True, upload_to='orders/%Y/%m/%d/', verbose_name='imagen del pago realizado')),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Cliente')),
                ('promo_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codes.promocode')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
