# Generated by Django 3.1.7 on 2021-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/%Y/%m/%d/', verbose_name='imagen del pago realizado'),
        ),
    ]
