# Generated by Django 3.1.7 on 2021-05-24 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='razón social'),
        ),
        migrations.AddField(
            model_name='order',
            name='ruc',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='El núm. de ruc no es válido, deben ser 10 números', regex='^\\+?1?\\d{9,10}$')], verbose_name='RUC'),
        ),
    ]
