# Generated by Django 3.1.7 on 2021-05-25 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210524_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='El núm. de ruc no es válido, deben ser 10 números', regex='^\\+?1?\\d{9,10}$')], verbose_name='RUC'),
        ),
    ]
