# Generated by Django 3.1.7 on 2021-04-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20210324_1648'),
        ('orders', '0002_order_payed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='Motorizado'),
        ),
    ]
