# Generated by Django 3.1.7 on 2021-04-13 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0002_auto_20210412_1722'),
        ('orders', '0004_auto_20210410_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='promo_codes.promocode'),
        ),
    ]
