# Generated by Django 3.1.7 on 2021-04-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RT', 'Registrado'), ('RC', 'Recepcionado'), ('OR', 'En Ruta'), ('DL', 'Entregado'), ('NDL', 'No Entregado'), ('RPR', 'Reprogramado'), ('CN', 'Cancelado')], default='RT', max_length=50, verbose_name='Estado'),
        ),
    ]
