# Generated by Django 3.1.7 on 2021-04-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210426_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='Código de seguimiento'),
        ),
    ]
