# Generated by Django 3.1.7 on 2021-04-29 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0003_paymentaccount'),
        ('orders', '0008_auto_20210427_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
        migrations.CreateModel(
            name='AssignOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='orders/delivered/%Y/%m/%d/', verbose_name='imagen o foto 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='orders/delivered/%Y/%m/%d/', verbose_name='imagen o foto 2')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='nota (opcional)')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.driver', verbose_name='motorizado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'asignar pedido',
                'verbose_name_plural': 'asignar pedidos',
            },
        ),
    ]
